spring:
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}

# Asiganmos un puerto de forma aleatoria
server:
  port: 5000

# Configuración Spring Doc
springdoc:
  packages-to-scan: com.formacion.controller
  paths-to-match: /**
