spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/cursosbd?serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082

# Configuración Spring Doc
springdoc:
  packages-to-scan: com.formacion.controller
  paths-to-match: /**
# La ruta Swagger: http://localhost:9000/swagger-ui/index.html
