spring:
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Asiganmos un puerto de forma aleatoria
server:
  port: 0

# Configuración Spring Doc
springdoc:
  packages-to-scan: com.formacion.controller
  paths-to-match: /**
