spring:
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8001

# Configuración Spring Doc
springdoc:
  packages-to-scan: com.formacion.controller
  paths-to-match: /**
# La ruta Swagger: http://localhost:9000/swagger-ui/index.html
