spring:
  application:
    name: 05-servicio-formacion
  cloud:
    config:
      #uri: http://localhost:8888  # Localización Spring Cloud Config
      fail-fast: true
      #allow-override: false
      #override-none: true
  config:
    import:
    - "optional:configserver:http://localhost:8888"

logging:
  level:
    '[org.springframework.cloud.config]': DEBUG
    '[org.springframework.boot.autoconfigure.jdbc]': DEBUG
    '[org.springframework.boot.web.embedded.tomcat]': DEBUG
